export interface Product {
  id: string;
  name: string;
  brand: string;
  designer: string;
  category: 'Furniture' | 'Lighting' | 'Accessories' | 'Art de la table';
  subCategory: string;
  description: string;
  basePriceEUR: number; // base price in EUR, converted dynamically
  image: string;
  gallery: string[];
  rating: number;
  reviewsCount: number;
  isBestSeller?: boolean;
  isReadyToShip?: boolean;
  isNew?: boolean;
  isSale?: boolean;
  discountPercent?: number;
  dimensions: string;
  materials: string;
  sku: string;
  designerBio?: string;
}

export interface CartItem {
  product: Product;
  quantity: number;
}

export interface Review {
  id: string;
  author: string;
  rating: number;
  date: string;
  content: string;
}

export interface CurrencyConfig {
  code: string;
  symbol: string;
  rateToEUR: number; // Multiply EUR by this to get local currency
  prefix: string;
}

export interface CountryConfig {
  code: string;
  name: string;
  flag: string;
  currency: string;
  language: string;
}

export const CURRENCIES: Record<string, CurrencyConfig> = {
  INR: { code: 'INR', symbol: '₹', rateToEUR: 90.15, prefix: '₹' },
  EUR: { code: 'EUR', symbol: '€', rateToEUR: 1.0, prefix: '€' },
  USD: { code: 'USD', symbol: '$', rateToEUR: 1.08, prefix: '$' },
  GBP: { code: 'GBP', symbol: '£', rateToEUR: 0.85, prefix: '£' }
};

export const COUNTRIES: CountryConfig[] = [
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR', language: 'English' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', currency: 'EUR', language: 'Italiano' },
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD', language: 'English' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP', language: 'English' }
];

export const PRODUCTS_DATA: Product[] = [
  {
    id: 'soriana-sofa',
    name: 'Soriana Sofa',
    brand: 'Cassina',
    designer: 'Afra & Tobia Scarpa',
    category: 'Furniture',
    subCategory: 'Sofas & Armchairs',
    description: 'Designed in 1969, the Soriana sofa is a revolutionary design classic. It is defined by its soft folds of rich fabric or leather wrapped in a large chrome metal clamp structure, achieving a perfect blend of informal comfort and high-end elegance.',
    basePriceEUR: 5200,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.9,
    reviewsCount: 28,
    isBestSeller: true,
    isReadyToShip: true,
    isSale: true,
    discountPercent: 12,
    dimensions: 'W: 175cm x D: 105cm x H: 71cm (Seat H: 42cm)',
    materials: 'Polyurethane and polyester fibers, chrome iron steel bracket, Premium Bouclé fabric upholstery',
    sku: 'CAS-SOR-001',
    designerBio: 'Afra and Tobia Scarpa are award-winning post-war Italian architects and designers. Their works can be found in major museums across Europe and USA.'
  },
  {
    id: 'camaleonda-sofa',
    name: 'Camaleonda Modular Sofa Group',
    brand: 'B&B Italia',
    designer: 'Mario Bellini',
    category: 'Furniture',
    subCategory: 'Modular Sofas',
    description: 'First introduced in 1970, Camaleonda has passed through 50 years of design history. Designed by Mario Bellini, this modular sofa defined the aesthetics of an entire era of interior design, featuring a capitonné tufted look generated by cable, hooks, and rings.',
    basePriceEUR: 7800,
    image: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 5.0,
    reviewsCount: 19,
    isBestSeller: true,
    isNew: true,
    dimensions: 'W: 288cm x D: 96cm x H: 67cm (Seat H: 40cm)',
    materials: 'Eco-felt fabric, polyurethane padding, rings in brass, stainless steel carabiners',
    sku: 'BBI-CAM-090',
    designerBio: 'Mario Bellini is an internationally renowned Italian architect and designer. He was awarded the Compasso d’Oro eight times and has 25 works in MoMA.'
  },
  {
    id: 'ic-t1-lamp',
    name: 'IC Lights T1 High Table Lamp',
    brand: 'Flos',
    designer: 'Michael Anastassiades',
    category: 'Lighting',
    subCategory: 'Table Lamps',
    description: 'An elegant form that explores balance. Designed by Michael Anastassiades, the IC Lights table lamp features a hand-blown glass sphere that appears to balance perfectly on the edge of a slanted brass-finish steel bar.',
    basePriceEUR: 490,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.8,
    reviewsCount: 45,
    isBestSeller: true,
    isReadyToShip: true,
    isSale: true,
    discountPercent: 10,
    dimensions: 'Height: 53cm x Sphere Diameter: 20cm x Base Width: 32.1cm',
    materials: 'Brushed brass structural steel, blown opal glass shade diffuser',
    sku: 'FLS-IC-T1H',
    designerBio: 'Michael Anastassiades launched his London design studio in 1994. Known for his minimalist, poetic lighting designs that balance geometry and light.'
  },
  {
    id: 'ph5-pendant',
    name: 'PH 5 Pendant Lamp White',
    brand: 'Louis Poulsen',
    designer: 'Poul Henningsen',
    category: 'Lighting',
    subCategory: 'Suspension Lamps',
    description: 'Designed in 1958 by Poul Henningsen, the PH 5 is a pioneering piece of lighting engineering. Its unique three-shade structure emits direct and indirect glare-free warm light, reflecting beautifully off the colored anti-glare rings within.',
    basePriceEUR: 890,
    image: 'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.9,
    reviewsCount: 34,
    isBestSeller: true,
    isReadyToShip: true,
    dimensions: 'Diameter: 50cm x Height: 26.7cm x Cable length: 300cm',
    materials: 'Spun aluminum shades with matte internal powder coating, frosted glass anti-glare shield',
    sku: 'LPO-PH5-W',
    designerBio: 'Poul Henningsen was a Danish designer, author, and architect who pioneered modern scientific lighting. His PH lighting system remains world-famous.'
  },
  {
    id: 'flowerpot-vp9',
    name: 'Flowerpot VP9 Portable LED Lamp',
    brand: '&Tradition',
    designer: 'Verner Panton',
    category: 'Lighting',
    subCategory: 'Portable Lamps',
    description: 'The beloved Flowerpot lamp by Verner Panton is now portable. In a slightly smaller size than the classic table version, this rechargeable cordless design brings cheerful 1968 counter-cultural style to your bedside, lounge, or outdoor dinner table.',
    basePriceEUR: 210,
    image: 'https://images.unsplash.com/photo-1543242595-c26124596399?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1543242595-c26124596399?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.7,
    reviewsCount: 79,
    isBestSeller: true,
    isReadyToShip: true,
    isSale: true,
    discountPercent: 15,
    dimensions: 'Diameter: 16cm x Height: 29.5cm',
    materials: 'Polycarbonate shade, steel charging port, LED light with 3-stage dimmer, USB recharge cable included',
    sku: 'AND-FLW-VP9-M',
    designerBio: 'Verner Panton was one of Denmark’s most influential 20th-century furniture and interior designers, celebrated for his futuristic, vibrant plastic designs.'
  },
  {
    id: 'eames-lounge-chair',
    name: 'Eames Lounge Chair & Ottoman',
    brand: 'Vitra',
    designer: 'Charles & Ray Eames',
    category: 'Furniture',
    subCategory: 'Armchairs & Lounge',
    description: 'Created in 1956, the Eames Lounge Chair and Ottoman represents the ultimate realization of high comfort, luxury materials, and craftsmanship. It combines molded plywood shells with premium leather, resulting in a lounge armchair that is a recognized museum masterpiece.',
    basePriceEUR: 6900,
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1581428982868-e410dd047a90?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 5.0,
    reviewsCount: 52,
    isBestSeller: true,
    dimensions: 'Chair: W: 84cm x D: 85cm x H: 84cm | Ottoman: W: 66cm x D: 56cm x H: 42cm',
    materials: 'Santos Palisander molded plywood veneer shells, die-cast aluminum rotatable base, black premium aniline leather upholstery',
    sku: 'VIT-EAM-LCO',
    designerBio: 'Charles and Ray Eames were an iconic American design duo whose architecture, graphics, and molded furniture transformed mid-century modern design.'
  },
  {
    id: 'tolomeo-micro',
    name: 'Tolomeo Micro Table Lamp',
    brand: 'Artemide',
    designer: 'Michele De Lucchi',
    category: 'Lighting',
    subCategory: 'Desk Lamps',
    description: 'Designed as a compact edition of the multi-award-winning Tolomeo, this elegant desk lamp incorporates a flexible cantilever arm system in polished aluminum. Balanced with spring tension, it allows precise, directable task lighting with minimal desk footprint.',
    basePriceEUR: 280,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.8,
    reviewsCount: 31,
    isReadyToShip: true,
    dimensions: 'Arm length details: H: max 73cm x Base Diameter: 17cm',
    materials: 'Polished aluminum base and cantilevered arms, spring joints, anodized aluminum diffuser',
    sku: 'ART-TOL-MIC',
    designerBio: 'Michele De Lucchi was a prominent figure in the Memphis design movement. His iconic Tolomeo workspace lamp won the Compasso d’Oro in 1989.'
  },
  {
    id: 'archibald-armchair',
    name: 'Archibald Armchair',
    brand: 'Poltrona Frau',
    designer: 'Jean-Marie Massaud',
    category: 'Furniture',
    subCategory: 'Armchairs & Lounge',
    description: 'The Archibald Armchair by Jean-Marie Massaud is a masterpiece of elegance and comfort. It features a beautifully draped, pleated leather upholstery that gathers elegantly on the inner backrest, set against a slender, minimal gunmetal metal base.',
    basePriceEUR: 3950,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.9,
    reviewsCount: 12,
    isNew: true,
    isReadyToShip: false,
    dimensions: 'W: 83cm x D: 80cm x H: 75cm (Seat H: 41cm)',
    materials: 'Steel structural frame, molded polyurethane foam padding, Pelle Frau® premium full-grain leather, cast aluminum legs',
    sku: 'PF-ARC-023',
    designerBio: 'Jean-Marie Massaud is a leading French architect and product designer. He focuses on natural shapes and elegance combined with technological innovation.'
  },
  {
    id: 'maralunga-sofa',
    name: 'Maralunga 40 Sofa',
    brand: 'Cassina',
    designer: 'Vico Magistretti',
    category: 'Furniture',
    subCategory: 'Sofas & Armchairs',
    description: 'An international bestseller and winner of Compasso d’Oro in 1979, the Maralunga sofa is highly acclaimed for its comfortable, adjustable fold-up headrests. It can change from low-back modern lounge style to tall-sitting full support in one smooth gesture.',
    basePriceEUR: 4900,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-155041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.9,
    reviewsCount: 16,
    isNew: true,
    dimensions: 'W: 190cm x D: 95cm x H: 72/100cm',
    materials: 'Internal steel skeleton, polyurethane foam core padding, velvet fabric cover, beech wood plinth feet',
    sku: 'CAS-MAR-040',
    designerBio: 'Vico Magistretti was a legendary Milanese architect and industrial designer whose products for Cassina and Artemide defined modern Italian design.'
  },
  {
    id: 'platner-side-table',
    name: 'Platner Structural Side Table',
    brand: 'Knoll',
    designer: 'Warren Platner',
    category: 'Furniture',
    subCategory: 'Tables & Desks',
    description: 'Designed in 1966, the Platner structural side table is constructed using a series of bent wire steel rods resembling a decorative sheaf of wheat. It captures an opulent, sculptural elegance with mid-century modern architectural integrity.',
    basePriceEUR: 1450,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.7,
    reviewsCount: 8,
    isReadyToShip: true,
    dimensions: 'Diameter: 40cm x Height: 46cm',
    materials: 'Curved vertical steel wire rods in polished nickel finish, clear tempered glass tabletop',
    sku: 'KNL-PLA-STB',
    designerBio: 'Warren Platner was an American architect and designer who worked alongside Raymond Loewy and Eero Saarinen before opening his famous Yale studio.'
  },
  {
    id: 'vitra-toolbox',
    name: 'Toolbox Storage Caddy',
    brand: 'Vitra',
    designer: 'Arik Levy',
    category: 'Accessories',
    subCategory: 'Desk Accessories',
    description: 'The Vitra Toolbox, designed by Arik Levy, is a elegant and practical organizer container. It holds hand accessories, office utensils, writing tools, and items cleanly with an integrated carrying handle, making it a design-lover desk essential.',
    basePriceEUR: 45,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.6,
    reviewsCount: 64,
    isReadyToShip: true,
    dimensions: 'W: 32.7cm x D: 16.7cm x H: 15.6cm',
    materials: 'Molded post-industrial recycled ABS plastic, sturdy central grab bar',
    sku: 'VIT-TLB-BLK',
    designerBio: 'Arik Levy is an artist and industrial designer known for his sculptural artworks, furniture, and practical lighting concepts for international brands.'
  },
  {
    id: 'georg-jensen-pitcher',
    name: 'HK Cobra Stainless Steel Water Pitcher',
    brand: 'Georg Jensen',
    designer: 'Henning Koppel',
    category: 'Art de la table',
    subCategory: 'Tableware',
    description: 'Designed originally by Danish master Henning Koppel, the Cobra Pitcher is famous for its sensual, fluid mirror-finished shape. It is beautiful to hold and pours seamlessly, serving as an art piece even when empty on the dining table.',
    basePriceEUR: 220,
    image: 'https://images.unsplash.com/photo-1617806118233-18e1db207f62?auto=format&fit=crop&q=80&w=800',
    gallery: [
      'https://images.unsplash.com/photo-1617806118233-18e1db207f62?auto=format&fit=crop&q=80&w=800'
    ],
    rating: 4.9,
    reviewsCount: 22,
    isReadyToShip: true,
    isNew: true,
    dimensions: 'W: 13cm x H: 33cm x Capacity: 1.2 Liter',
    materials: 'High-grade mirror polished 18/8 stainless steel',
    sku: 'GJS-HKB-PIT',
    designerBio: 'Henning Koppel was an artist and designer who pioneered the "organic functionalist" style that defined the luxurious Danish silverware aesthetic.'
  }
];
